### PR TITLE
Additional command line arguments

### PR DESCRIPTION
**Pull request by hovi**
Added --noinput --reverse and --failfast command line arguments to testrunners as per #39

### CODE REVIEW

**Comment by bittner** [comment]
Thanks for your PR!

Please address the build errors, and add tests for the new arguments. Thanks!

**Comment by hovi** [comment]
No worries, sorry for not checking tests. I took a quick look and I don't understand code much as it uses libraries I don't use. Will try to dig at weekend and fix it, but if it's something obvious that you can do fast on your own, then please do.

**Comment by bittner** [comment]
@hovi If you want to finish this please head on!

**Comment by bittner** [comment]
@hovi If you could rebase your changes onto `master` and make the build pass this could be a great contribution! Let us know if you need to discuss your changes to move on.

**Comment by bittner** [comment]
@hovi Any interest to take this PR further? Could be a useful feature.

**Comment by bittner** [comment]
I'm closing this PR in favor of PR #62.

I'm sorry, @hovi! Thanks for your efforts, anyway. :+1:

**Pull request closed without merging**
