### PR TITLE
Adds ability to modify the django runner class

### PR DESCRIPTION
**Pull request by kingbuzzman**

### CODE REVIEW

**Comment by bittner** [comment]
@kingbuzzman, can you explain the motivation in the PR body, also addressing the relation to PR #100, please?`And rebase your feature branch, so that the PR can be merged. Thank you!

**Comment by kingbuzzman** [comment]
> can you explain the motivation in the PR body, also addressing the relation to PR #100, please?
Adds the ability to add a custom Django facing TestRunner, this is different from #100 that changed the behave's TestRunner -- two different test cases.

> Also, is this an alternative solution to #123? Will it make that PR obsolete?
Yes, and yes?? Depending on which solution you prefer; I personally have an issue with #123.. I don't know if you do too. If @rodrigondec changes his approach to be more in line with how this is normally done, I have no issue supporting #123

**Comment by bittner** [comment]
@kingbuzzman Please don't forget to rebase your branch. There are conflicts which don't allow me to merge your changes.

**Comment by kingbuzzman** [comment]
I deleted the fork a while back, i have since re-forked it, but i have an issue that the branch is detached, i created a new PR https://github.com/behave/behave-django/pull/125

**Pull request closed without merging**
