### PR TITLE
Replace optparse by argparse, support Django 1.8 + 1.9 + 1.10

### PR DESCRIPTION
**Pull request by bittner**
This PR makes behave-django compatible with Django 1.10, finally replacing `optparse` by `argparse` in the management command.

To simplify the code, support for Django versions below 1.8 is dropped. All compatibility code (to support older versions) is removed. The obsolete integration hooks (deprecation warnings) are also removed.

This PR fixes: #2, #12, #17 

## Credits

Thanks @mixxorz for writing the tests for the CLI, specifically, which made it possible to do this refactoring.

### CODE REVIEW

**Comment by mixxorz** [comment]
Wow. This looks great. I think we can merge this in. I'll make a new release as soon as this is merged in. 👍

**Comment by bittner** [comment]
@mixxorz Will you merge this PR, or did you intend I should do it myself?

**Comment by PyDeq** [comment]
Cool, I'm eager :)

**Comment by mixxorz** [comment]
Oh sorry. Yeah I meant merge it in. 😀

**Comment by bittner** [comment]
@mixxorz Please, go ahead!

Note that the version number needs to bumped in [\_\_init\_\_.py](https://github.com/behave/behave-django/blob/master/behave_django/__init__.py#L3), I only updated it to `0.4.0.dev`.

Docs generation would also be cool.  Thank you!

**Comment by mixxorz** [comment]
Released 0.4.0

**Pull request merged**
