### PR TITLE
Scenarios should not change Feature Fixtures

### PR DESCRIPTION
**Pull request by bkuehlhorn**
Remove Scenario that changed Fixtures in Feature. Scenarios should not add Fixture that changes other Scenarios.

### CODE REVIEW

**Comment by bittner** [comment]
Okay, that just removes BDD examples that might not be optimal. But does it help any further?

The current example shows the possibilities. I think that was the point, originally.

**Comment by bittner** [comment]
See [the docs' usage chapter](http://behave-django.readthedocs.io/en/stable/usage.html#fixtures-in-environment-py) for reference:

> Of course, since `context.fixtures` is really just a list, you can mutate it however you want, it will only be processed upon leaving the `before_scenario()` function of your `environment.py` file.

**Comment by bkuehlhorn** [comment]
Because we can mutate context.fixtures does not mean we should. It impacts other Scenarios in the Feature. Documentation should not include sub-optimal examples.

**Comment by bkuehlhorn** [comment]
Because we can mutate context.fixtures does not mean we should. It impacts other Scenarios in the Feature. Documentation should not include sub-optimal examples.

**Comment by bkuehlhorn** [comment]
Because we can mutate context.fixtures does not mean we should. It impacts other Scenarios in the Feature. Documentation should not include sub-optimal examples.

**Comment by bittner** [comment]
Alright, but then include better examples. Not sure that simply removing things helps much.

**Comment by bittner** [comment]
@mixxorz Can you take a look at this PR?

**Comment by mixxorz** [comment]
Hang on. Setting `context.fixtures` in one scenario affects all other scenarios? What do you mean? I would say that's a bug.

```
def before_scenario(context, scenario):
        if scenario.name == 'User login with valid credentials':
            context.fixtures = ['user-data.json']
        elif scenario.name == 'Check out cart':
            context.fixtures = ['user-data.json', 'store.json', 'cart.json']
```

In this example, `user.data.json` gets loaded when the 'User login with valid credentials' and 'Check out cart' scenarios are run. Then, 'user-data.json', 'store.json', 'cart.json' get loaded when the 'Check out cart' scenario is run. @bkuehlhorn are you experiencing something different?

**Comment by bkuehlhorn** [comment]
@mixxorz In `Feature: Fixture loading`, switch the first 2 scenarios:
* Scenario: Load fixtures
* Scenario: Load fixtures for this scenario and feature

When I do this `Scenario: Load fixtures` fails when run second in the scenario. This is not a bug. Changing a Fixtures should not be done in `before_scenario`. Changes persist in all following Scenarios.

Documentation should not suggest this is appropriate.
Test should be removed or updated as a bad example.

**Comment by bkuehlhorn** [comment]
@mixxorz Have you been able to reproduce failure?

**Comment by mixxorz** [comment]
Sorry I haven't had the time. But I feel like we _should_ treat this as a bug. Ideally I'd want fixtures to be applied on a per-scenario basis, and I thought that was already the case.

**Comment by bittner** [comment]
@bkuehlhorn Do you think you can provide the changes necessary to have fixtures be applied on a per-scenario basis, as @mixxorz suggests?

**Comment by bittner** [comment]
@bkuehlhorn @mixxorz Any interest to take this PR further? Or should we close it?

**Comment by bkuehlhorn** [comment]
Loading fixtures for scenarios may require restarting test runner. That would be significant performance impact. It needs to remain as is

Yes, this should be closed

**Comment by bittner** [comment]
Closing as suggested by @bkuehlhorn.

**Pull request closed without merging**
