### PR TITLE
Add a "Related Topic" section to the sidebar (docs)

### PR DESCRIPTION
**Pull request by bittner**
This PR fixes issue #3 by adding links to the previous and next chapter of the documentation to the sidebar for each page. No "lost, where am I" syndrome anymore.

I also made some minor changes to the descriptive texts of the LaTeX version. Whatever!

### CODE REVIEW

**Comment by bittner** [comment]
@mixxorz Can you regenerate and upload the docs? Thanks!

**Comment by mixxorz** [comment]
Updated the docs 👍

**Comment by bittner** [comment]
Perfect, thank you! Now the navigation makes sense.

**Comment by bittner** [comment]
Oh, I've seen some links deserved being updated (Django -> `stable`, behave -> `latest` docs; commit 8f53a90). If you want you could update them online again, would be cool. Sorry about that!

**Comment by bittner** [comment]
:raising_hand: @mixxorz Would you mind re-creating and uploading the docs again? What disturbs me quite a bit is the link to the super-outdated [behave docs](http://pythonhosted.org/behave/django.html#automation-libraries) in the first note of the [installation chapter](http://pythonhosted.org/behave-django/installation.html). This is not helpful. :confused:

**Comment by mixxorz** [comment]
Reupped!

**Comment by bittner** [comment]
Thank you!  :+1:

**Pull request merged**
