### PR TITLE
Cover Python 3.7 + Django 2.1, drop Python 3.3 + Django < 1.11

### PR DESCRIPTION
**Pull request by bittner**
This PR does two big things:

1. Add Django 2.1 and Python 3.7, and all resulting combinations, to the list of test targets. At the same time we're dropping older Django versions and Python 3.3, which are not officially supported anymore. (In the spirit of @gvanrossum (I believe), I'm keeping the younger 2.x Django versions to have a continuous line of Djangos supported by Python 3 only.)
1. Change the test directory layout to a single `tests/` directory containing a `acceptance/` and a `unit/` directory for the two types of tests we're doing for this code base. This includes moving the `test_project` and `test_app` under the `tests/` directory. In addition, the BDD test layout in `tests/acceptance` is changed from the "minimum requirement for a features directory" to the "directory containing your feature files" layout variation ([as of the Behave documentation](https://behave.readthedocs.io/en/latest/gherkin.html#layout-variations)).

List of changes:
- Test against Django 2.1 and Python 3.7, drop Python 3.3 and Django 1.8 through 1.10
- Simplify packaging implementation (setup.py)
- Add Pipfile (the future replacement for `requirements*.txt`)
- Move features/ and unit tests to tests/ folder, change BDD directory layout for cleaner separation
- Show failed command output on error (Popen/run command)
- Move CLI test helpers to test utils

### CODE REVIEW

**Comment by bittner** [comment]
@sebastianmanger Could you do me a favor and analyze why the 2 test cases with the fixture annotation are failing?

- [Failing Travis job](https://travis-ci.org/behave/behave-django/jobs/444582057#L512-L514) (example)
- [Suspected code portion](https://github.com/behave/behave-django/blob/master/behave_django/environment.py#L26-L29) (program flow not entering this `if`-clause)

Thanks in advance for your support! :1st_place_medal:

**Comment by sebastianmanger** [comment]
@bittner Will take a look on the weekend! Cheers

**Comment by bittner** [comment]
> I am a bit out of the loop with behave, but tend to build on behaves fixture feature.

I have no strict preference here (mostly because it's not clear to me what the necessary changes look like), but it sounds more sustainable to build on a feature available and maintained in *behave*. :+1: 

Can you go for it? -- You'll probably have to start a new PR for it, and I need to merge the changes beforehand. You can't take advantage of the updates in this PR, otherwise. :thinking:

**Comment by bittner** [comment]
Any news on this, @sebastianmanger?

**Comment by bittner** [comment]
I'm merging this PR now as the failing builds are clearly related to the fixture decorator. And we now got this reported as a dedicated issue (#67).

A horrible compromise, as I don't like red builds in `master`, but heck, I don't want a long-living branch either! :worried:

**Pull request merged**
