### PR TITLE
Update URLs to repository, integrate contrib guide into docs, 

### PR DESCRIPTION
**Pull request by bittner**
* Integrate CONTRIBUTING file into docs
* Make README more concise (eliminating redundant Installation chapter)
* Add more badges (Gitter, license, Landscape)
* Update repo references to new project home (behave GitHub organization)
* Align document style in AUTHORS with HISTORY

### CODE REVIEW

**Comment by bittner** [comment]
Fixes [issue #54](https://github.com/mixxorz/behave-django/issues/54) in original repository.

**Comment by bittner** [comment]
@mixxorz You'll need to create an account on [Landscape](https://landscape.io/github/behave/behave-django/master) and adapt the Travis-CI configuration for the badges to work.

**Comment by mixxorz** [comment]
I made the Landscape account and configured Travis-CI for behave/behave-django

**Comment by bittner** [comment]
:+1:

**Pull request merged**
